import pandas as pd
from pyspark.sql import SparkSession
import pyspark.sql.functions as sf
from pyspark.sql.functions import col

# Start Spark Session
spark = SparkSession.builder.appName("OnlineRetailAnalyzer").getOrCreate()


# Read the excel file and convert it to a csv
df = pd.read_excel("Online Retail.xlsx", sheet_name = "Online Retail")
df.to_csv("online_retail.csv")


# Read the csv into a dataframe
data = spark.read.csv("online_retail.csv", header=True, inferSchema=True)


# Find out if there are any missing values by using dropna()
rows_before_drop = data.count()
data.dropna()
rows_after_drop = data.count()
print("Rows originally: " + str(rows_before_drop))
print("Rows after .dropna(): " + str(rows_after_drop))


# Find the total sales per country
country_sale_data = data.filter(col("Quantity") > 0).withColumn("TotalPrice", col("Quantity") * col("UnitPrice"))
country_sale_data.createOrReplaceTempView("Sales")
result = spark.sql("""SELECT Country, SUM(TotalPrice) AS TotalSales
                   FROM Sales
                   GROUP BY Country""")
result.show()


# Group the data by product name and sum the amount of them sold in each transaction
product_data = data.filter(col("Quantity") > 0)
product_data.createOrReplaceTempView("ProductSold")
top_5_products = spark.sql("""SELECT Description, SUM(Quantity) AS TotalSold
                           FROM ProductSold
                           GROUP BY Description
                           ORDER BY TotalSold DESC
                           LIMIT 5""")

top_5_products.show()

# Find the total revenue generated by the company
total_sales_data = data.filter(col("Quantity") > 0).withColumn("TotalPrice", col("Quantity") * col("UnitPrice"))
total_sales_data.createOrReplaceTempView("CompanyRevenue")
revenue_result = spark.sql("""SELECT SUM(TotalPrice) AS TotalSales
                           FROM CompanyRevenue""")
revenue_result.show()

spark.stop()


